version: '3'

services:

  nwtg2-db:
    image: postgres:latest
    hostname: nwtg2-db
    environment:
      - POSTGRES_PASSWORD=phohhairaetu

  nwtg2-rabbit:
    image: rabbitmq:3-management
    container_name: nwtg2-rabbit
    hostname: nwtg2-rabbit
    ports:
      - 15672:15672

  nwtg2-eureka:
    build:
      context: ./eureka-service
    container_name: nwtg2-eureka
    hostname: nwtg2-eureka

  nwtg2-apigw:
    build:
      context: ./api-gateway
    container_name: nwtg2-apigw
    hostname: nwtg2-apigw
    ports:
      - 8087:8087
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka

  nwtg2-authserver:
    build:
      context: ./authorization-server
    container_name: nwtg2-authserver
    hostname: nwtg2-authserver
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka

  nwtg2-datams:
    build:
      context: ./data-microservice
    container_name: nwtg2-datams
    hostname: nwtg2-datams
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka

  nwtg2-listms:
    build:
      context: ./list-microservice
    container_name: nwtg2-listms
    hostname: nwtg2-listms
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka

  nwtg2-streamms:
    build:
      context: ./stream-microservice
    container_name: nwtg2-streamms
    hostname: nwtg2-streamms
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka

  nwtg2-systemevents:
    build:
      context: ./system-events
    container_name: nwtg2-systemevents
    hostname: nwtg2-systemevents
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka

  nwtg2-userms:
    build:
      context: ./user-microservice
    container_name: nwtg2-userms
    hostname: nwtg2-userms
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka


  nwtg2-frontend:
    build:
      context: ./nwt-frontend
    container_name: nwtg2-frontend
    hostname: nwtg2-frontend
    ports:
      - 1112:80 # frontend se otvara na http://localhost:1112
    depends_on:
      - nwtg2-rabbit
      - nwtg2-apigw
      - nwtg2-authserver
      - nwtg2-datams
      - nwtg2-listms
      - nwtg2-streamms
      - nwtg2-systemevents
      - nwtg2-userms
