version: '3'

services:

  nwtg2-db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=phohhairaetu
    ports:
      - 5432:5432

  nwtg2-rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbit
    ports:
    - 5672:5672
    - 15672:15672

  nwtg2-eureka:
    build:
      context: ./eureka-service
    container_name: nwtg2-eureka
    hostname: eureka
    ports:
      - 8761:8761

  nwtg2-apigw:
    build:
      context: ./api-gateway
    container_name: nwtg2-apigw
    hostname: apigw
    ports:
      - 8087:8087
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka

  nwtg2-authserver:
    build:
      context: ./authorization-server
    container_name: nwtg2-authserver
    hostname: authserver
    ports:
      - 8093:8093
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka

  nwtg2-datams:
    build:
      context: ./data-microservice
    container_name: nwtg2-datams
    hostname: datams
    ports:
    - 8082:8082
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka

  nwtg2-listms:
    build:
      context: ./list-microservice
    container_name: nwtg2-listms
    hostname: listms
    ports:
    - 8083:8083
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka

  nwtg2-streamms:
    build:
      context: ./stream-microservice
    container_name: nwtg2-streamms
    hostname: streamms
    ports:
    - 8084:8084
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka

  nwtg2-systemevents:
    build:
      context: ./system-events
    container_name: nwtg2-systemevents
    hostname: systemevents
    ports:
    - 8089:8089
    depends_on:
      - nwtg2-db
      - nwtg2-rabbit
      - nwtg2-eureka
